- name: Create Pipeline Jobs
  ansible.builtin.include_tasks: import_tasks.yml
  loop:
    - {name: "frontend", dir: "CIPipelines"}
    - {name: "cart", dir: "CIPipelines"}
    - {name: "catalogue", dir: "CIPipelines"}
    - {name: "user", dir: "CIPipelines"}
    - {name: "payment", dir: "CIPipelines"}
    - {name: "shipping", dir: "CIPipelines"}

